language: java
jdk:
- oraclejdk8
branches:
  only:
    - master
install:
- mvn -version -B
script:
- git clone https://github.com/jkandasa/moquette
- mvn -f moquette/pom.xml install -Dmaven.test.skip=true
- mvn test
